### ISSUE TITLE
IN865 Frequency is not available 

### ISSUE THREAD

**Issue by salmanfarisvp** [PiSupply/pxt-iot-lora-node#45]
IN865 Used by India and it's missing in the microbit extension. 

![image](https://user-images.githubusercontent.com/11945360/117579386-3dd69c00-b110-11eb-8002-fe5722f67d63.png)

**Comment by acekapila** [comment]
Adding the IN865 directly into the extension library which is linked with MakeCode will help a lot in projects. 

Other references on internet are having bug or limitations due to MicroPython. 

Please update the extension with IN865.

**Comment by ryanteck** [comment]
The module does not support IN865, only the ones listed are currently supported.

**Comment by salmanfarisvp** [comment]
@ryanteck but IN865-867 is listed here on https://uk.pi-supply.com/products/iot-micro-bit-lora-node product page.

**Comment by acekapila** [comment]
@ryanteck I have ordered the product solely based on the product page from Pi-Supply. Also the Micro:Bit was ordered just because of this. 

Are you sure because then this is miss-information that you have on your product page, which people like me are trusting while making a purchase. 

Request you to please clarify.
